project:
  type: website
  output-dir: docs

website:
  title: "Corazón del Loto"
  navbar:
    logo: "images/logo.png"   # optional – remove or leave empty if you don't have one
    left:
      - href: index.qmd
        text: ¿Quiénes somos?
      - href: ceremonias.qmd
        text: Ceremonias 
      - href: cacao.qmd
        text: Cacao        
      - href: materiales.qmd
        text: Agenda
    page-footer:
    center: "© 2026 Olivia Almanza  y Salvador Ruiz"

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
 
