project:
  type: website
  output-dir: docs

website:
  title: "Corazón del Loto"
  navbar:
    logo: "images/logo.png"   # optional – remove or leave empty if you don't have one
    left:     
      - href: ceremonias.qmd
        text: Nuestras Ceremonias 
      - href: materiales.qmd
        text: Próximas Ceremonias
    page-footer:
    center: "© 2026 Olivia Almanza  y Salvador Ruiz"

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
 
